name: Docker Build and Push

on:
  push:
    branches: [main] # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # Build context (your project root)
          file: ./Dockerfile # Path to your Dockerfile
          push: true
          tags: woods334/githubTest:latest
          # Optional: Add build arguments
          build-args: |
            VERSION=1.0.0

        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Store your Docker Hub password as a GitHub secret